(() => {
 const toggle=document.querySelector('.demo-menu'), nav=document.querySelector('.demo-nav-links');
 toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open'); toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'Close':'Menu';});
 nav?.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false');if(toggle)toggle.textContent='Menu';}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='Menu';toggle.focus();}});
 matchMedia('(min-width:701px)').addEventListener('change',e=>{if(e.matches){nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');if(toggle)toggle.textContent='Menu';}});
 document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const result=form.querySelector('.demo-result');const data=new FormData(form);const kind=form.dataset.demoForm;let message='';if(kind==='construction')message=`Your sample brief: ${data.get('project')} — ${data.get('stage')}. A real site could now route this brief to the project team.`;if(kind==='wellness')message=`Your sample visit: ${data.get('ritual')}, ${data.get('time')}. A real booking system would confirm availability here.`;if(kind==='restaurant')message=`Your sample reservation: ${data.get('guests')} guests for ${data.get('sitting')}. A real booking system would check table availability here.`;result.textContent=message+' This is a design demonstration; nothing has been sent or booked.';result.hidden=false;result.focus();}));
 const dishes={dinner:[['Coal-roasted beetroot','Goat’s curd · smoked almond · sorrel','R135'],['Linefish over embers','Spring peas · preserved lemon · herb oil','R285'],['Karoo lamb','Aubergine · cultured cream · rosemary','R325'],['Dark chocolate crémeux','Olive oil · sea salt · roasted hazelnut','R125']],lunch:[['Garden plate','Seasonal leaves · crisp vegetables · seeds','R145'],['Wood-fired flatbread','Cultured yoghurt · tomato · garden herbs','R155'],['Roast chicken','Charred leeks · lemon · pan juices','R235'],['Stone fruit tart','Vanilla cream · almond · honey','R115']],wine:[['Chenin blanc','Coastal vineyards · fresh and textured','R85'],['Cinsault','Old vines · red fruit · light touch','R90'],['Cabernet sauvignon','Stellenbosch · structured and generous','R110'],['Cap classique','Traditional method · bright and elegant','R95']]};
 document.querySelectorAll('[data-menu]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-menu]').forEach(t=>t.setAttribute('aria-selected',String(t===tab)));const panel=document.querySelector('.terra-menu-list');panel.innerHTML=dishes[tab.dataset.menu].map(([t,d,p])=>`<article class="terra-dish"><h3>${t}</h3><span>${p}</span><p>${d}</p></article>`).join('');panel.setAttribute('aria-label',tab.textContent+' sample menu');}));
 document.querySelectorAll('[data-ritual]').forEach(link=>link.addEventListener('click',()=>{const select=document.querySelector('select[name="ritual"]');if(select)select.value=link.dataset.ritual;}));
 const tabs=[...document.querySelectorAll('[data-menu]')];
 const menuPanel=document.querySelector('.terra-menu-list');
 if(menuPanel){menuPanel.id='sample-menu-panel';tabs.forEach((tab,index)=>{tab.setAttribute('aria-controls',menuPanel.id);tab.tabIndex=index===0?0:-1;tab.addEventListener('click',()=>tabs.forEach(t=>t.tabIndex=t===tab?0:-1));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();tabs[next].click();}});});}
})();
