from pathlib import Path
import re, zipfile, sys
sys.stdout.reconfigure(encoding='utf-8')
root=Path(__file__).resolve().parent.parent
backup=zipfile.ZipFile(root/'design-review/before-redesign-2026-09-26.zip')
def original(name): return backup.read(name).decode('utf-8-sig')
def save(name,text): (root/name).write_text(text,encoding='utf-8')
logo='<a class="next-logo" href="index.html" aria-label="JNIT Cloud Solutions home"><span class="next-logo-art"><img src="01-Logos/JNIT-Stacked-Transparent.png" width="900" height="430" alt="JNIT Cloud Solutions (Pty) Ltd"></span></a>'
links=[('services.html','Services'),('work.html','Our work'),('web-development.html','Websites'),('applications.html','Applications'),('tools.html','Tools')]
def header(active):
    nav=''.join(f'<a href="{href}"'+(' aria-current="page"' if href==active else '')+f'>{label}</a>' for href,label in links)
    return f'<a class="next-skip" href="#main-content">Skip to content</a><header class="next-header">{logo}<button class="next-menu" type="button" aria-controls="next-navigation" aria-expanded="false">Menu</button><nav class="next-nav" id="next-navigation" aria-label="Main navigation">{nav}<a class="next-nav-cta" href="quote.html">Let’s talk <span aria-hidden="true">↗</span></a></nav></header>'
def footer():
    return f'''<footer class="next-footer"><div class="next-footer-inner"><div class="next-footer-top"><div><p class="next-eyebrow">Your next chapter</p><h2>Let’s make your<br>next move matter.</h2></div><a class="next-button light" href="quote.html">Discuss your project <span aria-hidden="true">↗</span></a></div><div class="next-footer-columns"><div>{logo}<p>Cloud solutions that grow with your business.</p><p>Independent digital engineering.<br>Johannesburg, South Africa.</p></div><div><h3>What we do</h3><a href="services.html">Cloud &amp; delivery</a><a href="applications.html">Web &amp; mobile apps</a><a href="web-development.html">Websites &amp; commerce</a></div><div><h3>Explore</h3><a href="work.html">Our work</a><a href="tools.html">Free tools</a><a href="store.html">Hardware store</a><a href="pawwatch.html">PawWatch</a></div><div><h3>Start a conversation</h3><a href="mailto:info@jnit.co.za">info@jnit.co.za ↗</a><a href="https://wa.me/27833297992">+27 83 329 7992 ↗</a><a href="quote.html">Prepare a project brief</a></div></div><div class="next-footer-bottom"><span>© <span class="next-year">2026</span> JNIT Cloud Solutions (Pty) Ltd</span><span>Design with purpose. Build with care.</span></div></div></footer>'''
def page(name,title,desc,body,extra=''):
    save(name,f'''<!doctype html>
<html lang="en-ZA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | JNIT Cloud Solutions</title><meta name="description" content="{desc}"><meta name="theme-color" content="#071421"><link rel="icon" href="assets/favicon.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="jnit-design.css?v=20260926"><script async src="https://www.googletagmanager.com/gtag/js?id=G-VRVRZRCNWW"></script><script src="site-metrics.js"></script></head>
<body class="next-site">{header(name)}<main id="main-content">{body}</main>{footer()}<script src="jnit-design.js?v=20260926"></script>{extra}</body></html>''')
def eyebrow(text): return f'<p class="next-eyebrow">{text}</p>'
def button(text,href,variant=''): return f'<a class="next-button {variant}" href="{href}">{text} <span aria-hidden="true">↗</span></a>'
def textlink(text,href): return f'<a class="next-text-link" href="{href}">{text} <span aria-hidden="true">↗</span></a>'
def hero(label,title,description,actions='',extra=''):
    return f'<section class="next-page-hero"><div class="next-wrap">{eyebrow(label)}<h1>{title}</h1><p>{description}</p>{actions}{extra}</div></section>'
def section(content,classes='',id=''):
    return f'<section class="next-section {classes}"'+(f' id="{id}"' if id else '')+f'><div class="next-wrap">{content}</div></section>'
def heading(label,title,description='',link=''):
    return f'<div class="next-heading-row"><div>{eyebrow(label)}<h2 class="next-section-title">{title}</h2></div>'+ (f'<p>{description}</p>' if description else link)+'</div>'
def demo_grid():
    return '<div class="next-demo-grid">'+''.join(f'<a href="demo-{key}.html"><div class="next-demo-image"><img src="images/demos/{key}-preview.webp" width="1440" height="1000" alt="{name} website design concept" loading="lazy"></div><h3>{name} ↗</h3><p>{tag}</p></a>' for key,name,tag in [('construction','Ironwood','Construction · Architectural and assured'),('wellness','Still','Wellness · Calm and considered'),('restaurant','Terra Noir','Hospitality · Warm and expressive')])+'</div>'+f'<article class="next-3d-feature"><a href="demo-3d.html" class="next-3d-image"><img src="images/demos/3d-preview.webp" width="1440" height="1000" alt="AURA interactive 3D lighting design concept" loading="lazy"></a><div>{eyebrow("A different dimension")}<h3>Don’t just show it.<br>Let people explore it.</h3><p>Meet AURA. A working 3D product experience with a rotatable lamp, three finishes and lighting you can change.</p>{button("Explore the 3D experience","demo-3d.html")}<span class="next-tag">Fictional product · Interactive demonstration</span></div></article>'
def process():
    items=[('Discover','Understand the problem, the people and what a useful outcome looks like.'),('Design','Make the experience and technical direction tangible before the build.'),('Develop','Build, test and refine the website, application and delivery foundation.'),('Deliver','Launch the agreed scope with documentation, handover and a clear next step.')]
    return '<div class="next-process">'+''.join(f'<article><span class="next-process-mark" aria-hidden="true">↗</span><h3>{t}</h3><p>{d}</p></article>' for t,d in items)+'</div>'

home=f'''<section class="next-home-hero next-dark"><div class="next-wrap"><div class="next-hero-grid"><div class="next-hero-copy">{eyebrow('Independent digital engineering')}<h1>Cloud Solutions<br>that grow <em>with<br>your business.</em></h1><p>Thoughtful websites. Purposeful applications. The cloud engineering that brings them together.</p><div class="next-actions">{button('Build with JNIT','quote.html')}{textlink('Explore our work','work.html')}</div></div><figure class="next-hero-art"><img src="images/brand/connected-form.webp" width="1536" height="1024" fetchpriority="high" alt="Sculptural silver and blue ribbons joining into one continuous form"><figcaption>Designed to connect. Engineered to grow.</figcaption></figure></div><div class="next-hero-meta"><div><span>Design <span>with purpose</span></span><span>Develop <span>with care</span></span><span>Deploy <span>with clarity</span></span></div><span class="next-location">Johannesburg · South Africa</span></div></div></section>'''
home+=section(f'<div class="next-intro">{eyebrow("One connected approach")}<h2>A better experience.<br>A stronger foundation.</h2><p>From the first interaction to the systems behind it, we bring design, development and cloud delivery into one considered build.</p></div>')
services=[('cloud-systems','Cloud &amp; delivery','A dependable foundation for the applications we develop or deploy. Architecture, automation and operational visibility.','services.html#cloud'),('digital-products','Web &amp; mobile apps','Useful software built around real people. From customer portals to business workflows and mobile experiences.','applications.html'),('digital-experiences','Websites &amp; commerce','A distinctive presence that makes your business easy to understand, trust and choose.','web-development.html')]
home+='<section class="next-wrap"><div class="next-services">'+''.join(f'<a class="next-service" href="{href}"><div class="next-service-visual"><img src="images/services/{key}.png" width="1024" height="1280" alt="{title} concept workspace" loading="lazy"><span aria-hidden="true">↗</span></div><h3>{title}</h3><p>{desc}</p></a>' for key,title,desc,href in services)+'</div><div class="next-services-note"><p>Cloud engineering supports the products JNIT develops or deploys for you. AWS is our primary platform; Azure and Google Cloud are available when the project calls for them.</p>'+textlink('Our capabilities','services.html')+'</div></section>'
home+=section(heading('Selected work','Real ideas.<br>Considered solutions.',link=textlink('View all projects','work.html'))+'''<div class="next-project-grid"><a class="next-project" href="pawwatch.html"><div class="next-project-visual"><img src="images/products/pawwatch/pawwatch-call-scene.webp" width="1600" height="900" alt="AI concept of two Jack Russells watching their caller on a television" loading="lazy"><span class="next-visual-note">AI concept illustration</span></div><div class="next-project-copy"><div><span class="next-tag">Personal build · Private use</span><h3>PawWatch</h3><p>A personal connection, from an iPhone away to the television at home.</p></div><b aria-hidden="true">↗</b></div></a><a class="next-project" href="applications.html#lifewallet"><div class="next-project-visual wallet"><span class="next-wallet-caption">Your money,<br>made clear.</span><img src="images/products/lifewallet-home.png" width="370" height="822" alt="LifeWallet Android preview" loading="lazy"></div><div class="next-project-copy"><div><span class="next-tag">Android preview · In development</span><h3>LifeWallet</h3><p>Everyday money management, designed to work on your device.</p></div><b aria-hidden="true">↗</b></div></a></div>'''+f'<div class="next-project-strip"><div><span class="next-tag">Engineering demonstration</span><h3>JNIT CloudOps</h3><p>Application delivery and AWS monitoring brought into one understandable system.</p></div>{textlink("Explore the case study","cloudops.html")}</div>')
home+=section(f'<div class="next-craft"><div>{eyebrow("Digital experiences")}<h2>Made for your<br>business.<br>Recognisably yours.</h2><p>Your website should feel like your business, from the first impression to the final enquiry. Explore four different directions, including an interactive 3D experience, in our working design concepts.</p>{textlink("Explore website design","web-development.html#demos")}</div><a class="next-craft-visual" href="demo-wellness.html" aria-label="Explore the Still Studio website concept"><img src="images/demos/wellness-preview.webp" width="1440" height="1050" alt="Still Studio wellness website concept" loading="lazy"><span>STILL STUDIO / WORKING DESIGN CONCEPT ↗</span></a></div>','next-dark')
home+=section(heading('Working with JNIT','Good work starts<br>with a clear conversation.','A defined scope, direct collaboration and care at every stage.')+process())
page('index.html','Cloud, applications & digital experiences','JNIT designs websites, develops web and mobile applications, and engineers the cloud behind the products we build or deploy.',home)

service_body=hero('Services / built together','The experience in front.<br><em>The engineering behind it.</em>','We design and build digital products, then create the cloud foundation and delivery workflows they need. One team, a clear scope, and a connected approach.',f'<div class="next-actions">{button("Discuss your build","quote.html")}</div>','<div class="next-subnav"><a href="#cloud">Cloud foundation</a><a href="#devops">Automated delivery</a><a href="#operations">Visibility &amp; resilience</a></div>')
rows=[('cloud','cloud-systems','Cloud foundation','A home for your product.','We define the infrastructure, dependencies and environments for applications JNIT develops or deploys. AWS is our primary platform. We can also develop, deploy and run your product on Azure or Google Cloud when required.',['Architecture matched to your application','Terraform infrastructure as code','Networking, identity and environments','Deployment validation and handover']),('devops','digital-products','DevOps &amp; automation','A clear path from code to release.','We connect source control, builds and deployment into a repeatable workflow for the products we deliver. Your team gets a system it can understand and continue using.',['GitHub Actions delivery workflows','Docker and container deployments','Infrastructure provisioning automation','Release documentation']),('operations','digital-experiences','Visibility &amp; resilience','Know how your product is doing.','We build useful monitoring, security and recovery foundations into the applications and platforms we deploy, with operational responsibilities agreed as part of the project.',['Metrics, logs and alerts','Identity and access foundations','Backup and recovery design','Cost visibility and documentation'])]
service_body+=section(''.join(f'<article class="next-service-row" id="{id}"><figure><img src="images/services/{im}.png" width="1024" height="1280" alt="{label} concept workspace" loading="lazy"></figure><div>{eyebrow(label)}<h2>{title}</h2><p>{desc}</p><ul class="next-tick-list">'+''.join(f'<li>{x}</li>' for x in points)+f'</ul>{textlink("Discuss your product build","quote.html?service="+id)}</div></article>' for id,im,label,title,desc,points in rows))
service_body+=section(heading('Connected capabilities','The rest of the picture.','Design, build and ongoing care for the work we deliver.')+'<div class="next-mini-grid">'+''.join(f'<article class="next-mini-card"><span class="next-tag">{tag}</span><h3>{title}</h3><p>{desc}</p>{textlink(cta,url)}</article>' for tag,title,desc,cta,url in [('Digital presence','Websites &amp; online stores','Distinctive business websites and commerce experiences. Defined packages from R3,500.','Explore websites','web-development.html'),('Digital products','Web &amp; mobile apps','Portals, workflows and Android or iOS experiences built around your users.','Explore applications','applications.html'),('Ongoing care','A considered next step','Hosting, maintenance, updates and backups for websites JNIT delivers.','Discuss website care','quote.html?service=care')])+'</div>','next-muted')
service_body+=section(heading('How we work','From a useful idea<br>to a defined build.')+process())
page('services.html','Services','Cloud engineering, automated delivery and software development for products JNIT develops or deploys on AWS, Azure or Google Cloud.',service_body)

def wallet_feature():
    return f'''<article class="next-feature dark" id="lifewallet"><div class="next-feature-copy"><span class="next-tag">Android preview · Active development</span><h2>LifeWallet</h2><p><strong>Your money, made clear.</strong></p><p>A local-first personal money app for cash flow, budgets, bills, accounts and safe-to-spend guidance. Core features work without internet access or registration.</p><ul class="next-tick-list"><li>Local accounts and cash transactions</li><li>Budgets and recurring bills</li><li>Reviewed statement imports</li><li>Reports and encrypted backups</li></ul>{textlink('Ask about the Android preview','mailto:info@jnit.co.za?subject=LifeWallet%20Android%20preview')}</div><div class="next-feature-visual phone"><img src="images/products/lifewallet-home.png" width="370" height="822" alt="LifeWallet Android home screen" loading="lazy"></div></article>'''
def small_products():
    return '<div class="next-mini-grid">'+''.join(f'<article class="next-mini-card" id="{id}"><span class="next-tag">{tag}</span><h3>{name}</h3><p>{desc}</p>{textlink(cta,url)}</article>' for id,tag,name,desc,cta,url in [('travel','Private pilot','Travellers Companion','Travel documents, itineraries, maps, calendars and a private family gallery, brought together in one trip.','Ask about the pilot','mailto:info@jnit.co.za?subject=Travellers%20Companion%20pilot'),('customs','In development','Customs Workflow Platform','Controlled document intake, assignment, operational queues and audit-ready retrieval for logistics teams.','Request a private demo','mailto:info@jnit.co.za?subject=Customs%20Workflow%20demo'),('website-concepts','Working demonstrations','Website concepts','Four distinctive experiences: construction, wellness, hospitality and an interactive 3D product showcase.','Explore the concepts','web-development.html#demos')])+'</div>'
work=hero('Selected builds & concepts','Ideas made tangible.<br><em>Engineering made visible.</em>','A closer look at the problems we’re solving and the experiences we’re building. Personal builds, product previews and working demonstrations, with their current stages clearly shown.')
work+=section(f'''<article class="next-feature"><div class="next-feature-copy"><span class="next-tag">Engineering demonstration · Validated on AWS</span><h2>JNIT CloudOps</h2><p>A clearer view of deployment progress, service health and operational signals across a cloud workload.</p><p>Cloud architecture, automated delivery and monitoring, brought into one understandable system.</p><p class="next-disclosure">A demonstration environment built and validated on AWS. The case study shows captured evidence; it is not a continuously running production service.</p>{textlink('Explore the CloudOps case study','cloudops.html')}</div><div class="next-feature-visual"><img src="images/cloudops/monitoring-live.png" width="1600" height="900" alt="Captured JNIT CloudOps AWS monitoring dashboard" loading="lazy"></div></article>'''+wallet_feature()+f'''<article class="next-feature"><div class="next-feature-copy"><span class="next-tag">Personal build · Private use</span><h2>PawWatch</h2><p>Stay close, even from far away. A private iPhone-to-TV video connection built for a traveller and two Jack Russells at home.</p>{textlink('See the PawWatch story','pawwatch.html')}<p class="next-disclosure">AI concept imagery illustrates the experience.</p></div><div class="next-feature-visual" style="padding:0"><img style="height:100%;object-fit:cover;border-radius:0" src="images/products/pawwatch/pawwatch-call-scene.webp" width="1600" height="900" alt="AI concept of the PawWatch television call with two Jack Russells" loading="lazy"></div></article>'''+small_products())
page('work.html','Our work','Explore JNIT CloudOps, LifeWallet, PawWatch, private product pilots and working website concepts.',work)

apps=hero('Web & mobile applications','Useful by design.<br><em>Built around your world.</em>','Give your customers a simpler experience and your team better tools. We develop web platforms and mobile applications around the way your business works.',f'<div class="next-actions">{button("Discuss your application","quote.html?service=application")}{textlink("Explore our builds","#products")}</div>')
apps+=section(heading('Software with a purpose','On the web. In their pocket.<br>Working together.')+'<div class="next-mini-grid">'+''.join(f'<article class="next-mini-card"><span class="next-tag">{tag}</span><h3>{title}</h3><p>{desc}</p></article>' for tag,title,desc in [('Web platforms','A workspace that fits.','Customer portals, internal dashboards, booking systems and workflow tools accessible through a browser.'),('Mobile applications','Your service, within reach.','Android and iOS applications, with features and integrations selected for your audience and devices.'),('Connected systems','Less friction behind the scenes.','APIs, authentication and cloud infrastructure that support the complete experience.')])+'</div>')
apps+=section(heading('Our product work','Ideas taking shape.','Explore what we’re working on, with each product’s current stage shown below.')+wallet_feature()+f'<article class="next-app-pawwatch" id="pawwatch"><div><span class="next-tag">Personal build · Private use</span><h2>PawWatch</h2><p>A private iPhone-to-TV connection, built to stay close to two dogs while travelling.</p></div>{textlink("View the project","pawwatch.html")}</article>'+small_products(),'next-muted','products')
page('applications.html','Web & mobile applications','JNIT develops web platforms, mobile applications and connected workflows. Explore LifeWallet, PawWatch and our product work.',apps)

oldweb=original('web-development.html')
packages=re.search(r'(<div class="package-grid">.*?)(?=</section><section class="section demo-collection")',oldweb,re.S)
if not packages: raise RuntimeError('Original pricing content not found')
faq=re.search(r'<div class="faq-list">.*?</div></section>',oldweb,re.S).group(0).removesuffix('</section>')
web=f'<section class="next-page-hero"><div class="next-wrap next-web-hero"><div>{eyebrow("Websites & commerce")}<h1>A first impression.<br><em>A lasting connection.</em></h1><p>A website with a point of view, a clear purpose, and an experience that feels right on every screen.</p><div class="next-actions">{button("Find your starting point","#packages")}{textlink("See our concepts","#demos")}</div></div><figure><img src="images/demos/construction-preview.webp" width="1440" height="1050" alt="Ironwood construction website design concept"><figcaption>IRONWOOD / A JNIT WORKING DESIGN CONCEPT</figcaption></figure></div></section>'
web+=section(heading('Considered from the start','More than a good-looking page.','Clear content, thoughtful interactions and a sound technical foundation.')+'<div class="next-process">'+''.join(f'<article><h3>{t}</h3><p>{d}</p></article>' for t,d in [('Clarity','Make it easy to understand your business and take the next step.'),('Character','A visual direction shaped around your brand and audience.'),('Performance','Responsive layouts and carefully prepared assets.'),('Room to grow','A considered structure for content, commerce and future features.')])+'</div>')
web+=section(heading('Design explorations','Different businesses.<br>Different expressions.','Working demonstration concepts created for different audiences. These are design explorations, not client commissions.')+demo_grid()+'<p class="next-fineprint">Demo booking and estimate actions illustrate the experience. Live bookings, payments and integrations are scoped for your project.</p>','next-muted','demos')
web+=section(heading('Website packages','A clear starting point.','Launch pricing for South African businesses. Every project starts with a conversation about the scope and outcome.')+packages.group(1),'','packages')
web+=section(f'<div class="next-faq"><div>{eyebrow("Before we begin")}<h2>Straight answers.<br>Clear expectations.</h2></div>{faq}</div>','next-muted')
page('web-development.html','Website design & development','Distinctive business websites and online stores from JNIT. Explore working design concepts and website packages from R3,500.',web)

q=original('quote.html')
form=re.search(r'<form id="project-brief">.*?</form>',q,re.S).group(0)
form=re.sub(r'<label><input type="radio" name="project" value="Microsoft 365, security or IT consulting">.*?</label>','',form,flags=re.S)
form=form.replace('Cloud infrastructure or migration','Cloud foundation for a client product developed or deployed by JNIT').replace('Cloud & infrastructure<small>Architecture, migrations or support','Cloud foundation<small>For a product JNIT develops or deploys')
form=form.replace('For example: automate deployments, move a workload to AWS, improve monitoring, or build a new application','Tell us what you want to build, who will use it and what should work better.')
enquiry=f'<div class="next-wrap next-enquiry"><section class="next-enquiry-intro">{eyebrow("Start a conversation")}<h1>Your next step.<br><em>Let’s work it out.</em></h1><p>Tell us what you have in mind. We’ll help turn the idea into a clear scope and a practical way forward.</p><a href="mailto:info@jnit.co.za">info@jnit.co.za ↗</a><a href="https://wa.me/27833297992">Chat on WhatsApp ↗</a><ul><li><strong>A conversation first.</strong><br>Your first consultation is free.</li><li><strong>Direct collaboration.</strong><br>Speak with the person delivering the work.</li><li><strong>A defined scope.</strong><br>Know what’s included before the build.</li></ul></section><section aria-label="Prepare your project brief">{form}</section></div>'
page('quote.html','Let’s build your next step','Talk to JNIT about your next website, application or cloud-supported product. Prepare a project brief or contact us directly.',enquiry,'<script src="quote.js"></script>')

# Preserve working calculators, store and full case studies; use the new shell everywhere.
core={'index.html','services.html','work.html','applications.html','web-development.html','quote.html'}
retrofitted=[]
for name in backup.namelist():
    if '/' in name or not name.endswith('.html') or name in core or name.startswith('demo-') or name=='store-backup.html': continue
    src=original(name)
    if 'class="site-header' not in src: continue
    src=re.sub(r'<a class="skip-link".*?</a>','',src,flags=re.S)
    src=re.sub(r'<header\b.*?</header>',header(name),src,count=1,flags=re.S)
    src=re.sub(r'<footer\b.*?</footer>',footer(),src,count=1,flags=re.S)
    src=src.replace('</head>','<link rel="stylesheet" href="jnit-design.css?v=20260926"></head>')
    src=re.sub(r'<body class="([^"]*)"',lambda m:'<body class="'+m.group(1)+' next-site legacy-page"',src,count=1)
    src=src.replace('</body>','<script src="jnit-design.js?v=20260926"></script></body>')
    # The form labels now define product scope rather than general managed IT services.
    if name=='tools.html':
        src=re.sub(r'<section class="page-hero">.*?</section>',hero('JNIT toolkit','Small tools.<br><em>Useful answers.</em>','Practical calculators, planners and checklists to help you make sense of technical decisions. Explore the toolkit below.'),src,count=1,flags=re.S)
        src=src.replace('<h2>Find the right tool for the job.</h2>','<h2>A little clarity goes a long way.</h2>')
    save(name,src); retrofitted.append(name)
save('.superdesign/design-system.md','''# JNIT / Connected craft
Independent digital engineering. Original composition, based on JNIT content.
Navy #071421, paper #f5f4f0, electric blue #0965ee, ice #94c6ff.
Manrope 550–650 headings; DM Sans 400–650 body. Body 17px; labels 12px.
Max content 1440px, fluid 22–104px margins, restrained 14px image corners.
Approved JNIT logo only. Clear current project status. No vendor badge strips.
Cloud services support products JNIT builds/deploys; AWS primary, Azure/GCP as required.
Header and footer shared. Main pages use jnit-design.css directly; tools preserve functionality.
Research: https://work.co/ , https://linear.app/ , https://www.thoughtworks.com/ . Reviewed for clarity of positioning and product-led storytelling, not copied.
''')
print('Rebuilt core pages:',', '.join(sorted(core)))
print('Updated shared presentation:',', '.join(retrofitted))
